# Generated by Django 3.2.15 on 2023-05-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_ordercontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercontent',
            old_name='product',
            new_name='item',
        ),
    ]
