# Generated by Django 3.2.15 on 2023-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230607_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Cook'), ('D', 'Delivery'), ('R', 'Ready')], default='N', max_length=2),
        ),
    ]
