# Generated by Django 3.2.15 on 2023-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Необработанный'), ('C', 'Готовится'), ('D', 'Передан в доставку'), ('R', 'Выполнен')], default='N', max_length=2),
        ),
    ]
