# Generated by Django 3.2.15 on 2023-06-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=None, max_digits=8, verbose_name='расстояние')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.order', verbose_name='расстояние')),
                ('restaurant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant')),
            ],
            options={
                'unique_together': {('order', 'restaurant')},
            },
        ),
    ]
