# Generated by Django 3.2.15 on 2023-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_orderdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdistance',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='расстояние'),
        ),
    ]
