# Generated by Django 3.2.15 on 2023-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('C', 'Наличные'), ('E', 'Электронно')], db_index=True, default=None, max_length=2, verbose_name='метод оплаты'),
        ),
    ]
