# Generated by Django 3.2.15 on 2023-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20230626_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='registered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('C', 'Наличные'), ('E', 'Электронно')], db_index=True, max_length=2, verbose_name='метод оплаты'),
        ),
    ]
