# Generated by Django 3.2.15 on 2024-02-12 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_ordercontent_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('lat', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='широта')),
                ('lon', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='долгота')),
            ],
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='orderdistance',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderdistance',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
