# Generated by Django 3.2.15 on 2024-02-15 12:12

from django.db import migrations, models
import django.db.models.deletion
from restaurateur.geo_utils import fetch_coordinates
from geopy import distance
from foodcartapp.models import Distances


def clear_distances(apps, schema_editor):
    OrderDistance = apps.get_model('foodcartapp', 'OrderDistance')
    for order_distance in OrderDistance.objects.all():
        order_distance.distance = None
        order_distance.save()


def copy_distances_to_own_table(apps, schema_editor):
    Distances = apps.get_model('foodcartapp', 'Distances')
    OrderDistance = apps.get_model('foodcartapp', 'OrderDistance')
    Address = apps.get_model('foodcartapp', 'Address')
    for order_distance in OrderDistance.objects.all():
        addr_1 = order_distance.restaurant.address
        (lat1, lon1) = fetch_coordinates(addr_1)
        restaurant_address, create = Address.objects.get_or_create(lat=lat1, lon=lon1, address=addr_1)
        addr_2 = order_distance.order.address
        (lat2, lon2) = fetch_coordinates(addr_2)
        order_address, create = Address.objects.get_or_create(lat=lat2, lon=lon2, address=addr_2)
        dist = distance.distance((lat1, lon1), (lat2, lon2)).km
        dist_obj, create = Distances.objects.get_or_create(address_1=restaurant_address, address_2=order_address, distance=dist)
        order_distance.distance = dist_obj
        order_distance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20240212_0645'),
    ]

    operations = [
        migrations.RunPython(clear_distances),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True, verbose_name='расстояние')),
                ('address_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_1', to='foodcartapp.address', verbose_name='адрес 1')),
                ('address_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_2', to='foodcartapp.address', verbose_name='адрес 2')),
            ],
            options={
                'unique_together': {('address_1', 'address_2')},
            },
        ),
        migrations.AlterField(
            model_name='orderdistance',
            name='distance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.distances', verbose_name='расстояние'),
        ),
        migrations.RunPython(copy_distances_to_own_table),
    ]
