# Generated by Django 3.2.15 on 2024-04-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_alter_orderdistance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
